name: Deploy Coding Tracker Server
on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'Azure Web App Name'
        required: true
        default: 'app-vscode-coding-tracker'
      uploadToken:
        description: 'Upload Token for the server'
        required: true
        default: ''
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ github.event.inputs.appName }}
          package: .