name: Deploy Coding Tracker Server
on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'Azure Web App Name'
        required: true
        default: 'app-vscode-coding-tracker'
      uploadToken:
        description: 'Upload Token for the server'
        required: true
        default: ''
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: YOUR_GITHUB_USERNAME/vscode-coding-tracker-server # Checkout your forked server repository
          path: server-code

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Remove node-sass dependency
        run: |
          jq 'del(.dependencies."node-sass") | del(.devDependencies."node-sass")' package.json > package.json.tmp && mv package.json.tmp package.json
        working-directory: server-code

      - name: Install Dependencies
        run: |
          npm install --omit=dev
        working-directory: server-code

      # - name: Test Server (Optional)
      #   run: |
      #     npm run test
      #   working-directory: server-code

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: server-code